//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int InventoryItemId { get; set; }
        public string InventoryItemName { get; set; }
        public int InventoryType { get; set; }
    
        public virtual InventoryType InventoryType1 { get; set; }
    }
}
